POST http://localhost:8081/invoices?user_id=freddieFox&amount=50
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:8081/invoices
Accept: application/json

###
GET http://localhost:8082/transaction
Accept: application/json

###
POST  http://localhost:8082/transaction?amount=50&reference=freddieFoxing
Accept: application/json
